### ISSUE TITLE
ImportError after Creating First Project - 'module pinax has no main attribue'

### ISSUE THREAD

**Issue by nicorellius** [pinax/pinax#110]
Greetings,

I'm new to `pinax` and I think it's awesome. The following report could be a result of me not knowing what I'm doing. But if it's a bug, then I wanted to give as detailed report as possible.

What happened

1. Followed instructions to start new starter project. I've tried with several starters, eg, `documents`, `wiki`, `account`, etc.
2. This works fine, eg, `pinax start --dev documents mysite` completes and I can start server and view site.
3. All subsequent use of the `pinax` command fails with the following trace:

        Traceback (most recent call last):
		File "/home/nick/dev/virtenvs/pindocs/bin/pinax", line 9, in <module>
		    load_entry_point('pinax-cli==0.4', 'console_scripts', 'pinax')()
		File "/home/nick/dev/virtenvs/pindocs/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
		    return get_distribution(dist).load_entry_point(group, name)
		File "/home/nick/dev/virtenvs/pindocs/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
		    return ep.load()
		File "/home/nick/dev/virtenvs/pindocs/local/lib/python2.7/site-packages/pkg_resources.py", line 2053, in load
		    raise ImportError("%r has no %r attribute" % (entry,attr))
		ImportError: <module 'pinax' from '/home/nick/dev/virtenvs/pindocs/local/lib/python2.7/site-packages/pinax/__init__.pyc'> has no 'main' attribute

What should've happened

I would expect the `pinax` command to still work, eg, be able to list projects with `pinax projects`.

Steps to reproduce

Versions: Ubuntu 14.04, Python 2.7.6, virtualenv 1.11.4, pinax 0.4:

    lssitepackages | grep pinax_cli
    pinax_cli-0.4-py2.7.egg-info

These are the steps I used to get the trace:

    mkvirtualenv mysite
    pip install pinax-cli
    pinax start account mysite
    cd mysite
    chmod +x manage.py
    pip install -r requirements.txt
    ./manage.py migrate
    ./manage.py loaddata sites
    ./manage.py runserver

Server is running, site visible at `http://localhost:8000`.

Now run `pinax projects`. Error should appear.

**Comment by nicorellius** [comment]
My apologies... I see this was fixed in issue 105. I'll close.
