### ISSUE TITLE
start account fails with tarfile.ReadError on PythonAnywhere

### ISSUE THREAD

**Issue by hjwp** [pinax/pinax#124]
Originally reported at https://www.pythonanywhere.com/forums/topic/9094/

```
Traceback (most recent call last):
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/bin/pinax", line 11, in <module>
    sys.exit(main())
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/pcli.py", line 98, in start
    start_project(projects[project], name, dev)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/pcli.py", line 35, in start_project
    call_command("startproject", name, **kwargs)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in c
all_command
    return command.execute(*args, **defaults)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/commands/startproject.py", line 34, in handle
    super(Command, self).handle('project', project_name, target, **options)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/templates.py", line 126, in handle
    base_subdir)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/templates.py", line 213, in handle_template
    return self.extract(absolute_path)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/core/management/templates.py", line 314, in extract
    archive.extract(filename, tempdir)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/utils/archive.py", line 49, in extract
    with Archive(path) as archive:
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/utils/archive.py", line 58, in __init__
    self._archive = self._archive_cls(file)(file)
  File "/home/username/.virtualenvs/tmp-9e86ffb6d8936815/local/lib/python2.7/site-packages/django/utils/archive.py", line 137, in __init__
    self._archive = tarfile.open(file)
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

May be due to the limitations of a PythonAnywhere free account, the most likely of which is the Internet access being restricted to a [whitelist](https://www.pythonanywhere.com/whitelist/) -- does the pinax start account command try to access any external sites (that aren't on that list)?

**Comment by KatherineMichel** [comment]
@hjwp Based on the PythonAnywhere ticket, it appears that this was an issue with free account. Presumably the issue can be closed now? The pinax-cli code is online and does use JSON scripts found on GitHub. This could be good FAQ info to add to our docs. https://github.com/pinax/pinax-cli
